#!/bin/sh

if [ -n "$1" ]; then
    xdg-open "$1" >/dev/null 2>&1
else
    doc=$(fd --hidden --no-ignore --type f\
        --extension ".pdf"\
        --extension ".xps"\
        --extension ".epub"\
        --extension ".djvu"\
        . "$(xdg-user-dir DOCUMENTS)" | fzf --header "View selected document.")
    [ -z "$doc" ] || xdg-open "$doc" >/dev/null 2>&1
fi
