#!/bin/sh
# shellcheck disable=SC2016

while read -r file; do
    case "$1" in
        "w")
            sed -i "s|^export PAPE.*|export PAPE=\"$(realpath "$file" | sed "s|/home/rfacun/media/pictures|$(xdg-user-dir PICTURES)|g")\"|g" "$HOME/.profile"
            xwallpaper --maximize "$file" ;;
        "s") cp "$(realpath "$file")" "$SCREENSAVERS/$(basename "$file")" ;;
        "r") rm "$file" ;;
        "p") realpath "$file" | xclip -selection clipboard ;;
    esac
done
