#!/bin/bash
# Installation script for Arch Linux

### FUNCTIONS

info_message() {
    printf "\033[93;1m${1}\n\033[0m"
}

error_message() {
    printf "\033[91;1m${1}\n\033[0m"
}

success_message() {
    printf "\033[92;1m${1}\n\033[0m"
}


# INITIAL CONFIG
loadkeys la-latin1
setfont /usr/share/kbd/consolefonts/ter-c16b.psf.gz
timedatectl set-ntp true


# FORMATTING
# To-Do
#   - add device variable
#   - check and convert BIOS to UEFI
#       https://wiki.manjaro.org/index.php/UEFI_-_Install_Guide#Switching_from_BIOS_to_UEFI
#   - check and convert MBR to GPT
#       https://www.rodsbooks.com/gdisk/mbr2gpt.html
info_message ">> PARTITIONING DRIVES"
umount -A --recursive /mnt                      # Make sure everything is unmounted
sgdisk --zap-all /dev/sda                       # Destroy GPT and MBR data structures
sgdisk --set-alignment=2048 --clear /dev/sda    # Make new GPT alignment
# Create partitions
sgdisk --new=1::+512M --typecode=1:EF00 --change-name=1:'EFIBOOT' /dev/sda  # EFI partition
sgdisk --new=2::+8G --typecode=2:8200 --change-name=2:'SWAP' /dev/sda       # Swap partition
sgdisk --new=3::-0 --typecode=3:8300 --change-name=3:'ROOT' /dev/sda        # Root partition
partprobe /dev/sda          # Re-read partition table to make sure it is correct
success_message ">> DONE!"


# FILE SYSTEM
# To-Do
#   - make formatting and file system modular so I can use variables
# Create the file systems
info_message ">> CREATING FILE SYSTEMS AND MOUNTING PARTITIONS"
mkfs.fat -F32 /dev/sda1
mkswap /dev/sda2
mkfs.ext4 /dev/sda3
# Mount the partitions
mount --mkdir /dev/sda1 /mnt/boot
swapon /dev/sda2
mount /dev/sda3 /mnt
success_message ">> DONE!"


# INSTALLATION
info_message ">> INSTALLING ARCH LINUX"
pacstrap -K /mnt base base-devel linux linux-firmware git unzip
genfstab -U /mnt >> /mnt/etc/fstab
success_message ">> DONE!"


# TIMEZONE
info_message ">> SETTING UP TIMEZONE"
arch-chroot /mnt /bin/bash -c "ln -sf /usr/share/zoneinfo/America/Argentina/Buenos_Aires /etc/localtime"
arch-chroot /mnt /bin/bash -c "hwclock --systohc"   # Set the hardware clock from the system clock
success_message ">> DONE!"


# LOCALIZATION
info_message ">> SETTING UP LOCALIZATION"
arch-chroot /mnt /bin/bash -c "sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen"
arch-chroot /mnt /bin/bash -c "sed -i 's/^#en_US ISO-8859-1/en_US ISO-8859-1/' /etc/locale.gen"
arch-chroot /mnt /bin/bash -c "locale-gen"
# Language
arch-chroot /mnt /bin/bash -c "echo 'LANG=en_US.UTF-8' >> /etc/locale.conf"
arch-chroot /mnt /bin/bash -c "echo 'LANGUAGE=en_US:C' >> /etc/locale.conf"
# Keyboard
arch-chroot /mnt /bin/bash -c "echo 'KEYMAP=la-latin1' >> /etc/vconsole.conf"
success_message ">> DONE!"


# NETWORK
info_message ">> SETTING UP NETWORK"
arch-chroot /mnt /bin/bash -c "echo 'sagittarius' >> /etc/hostname"
arch-chroot /mnt /bin/bash -c "echo '
27.0.0.1    localhost
::1         localhost
27.0.1.1    sagittarius.localdomain sagittarius' >> /etc/hosts"
arch-chroot /mnt /bin/bash -c "pacman -S --noconfirm --needed networkmanager"
arch-chroot /mnt /bin/bash -c "systemctl enable NetworkManager"
success_message ">> DONE!"


# BOOTLOADER
info_message ">> SETTING UP THE BOOTLOADER (GRUB)"
arch-chroot /mnt /bin/bash -c "pacman -S --noconfirm --needed grub efibootmgr mtools dosfstools os-prober"
arch-chroot /mnt /bin/bash -c "mkdir /boot/EFI"
arch-chroot /mnt /bin/bash -c "mount /dev/sda1 /boot/EFI"
arch-chroot /mnt /bin/bash -c "grub-install --target=x86_64-efi --bootloader-id=SAGITTARIUS --efi-directory=/boot/EFI --recheck"
arch-chroot /mnt /bin/bash -c "grub-mkconfig -o /boot/grub/grub.cfg"
success_message ">> DONE!"


# USER
info_message ">> ENTER ROOT PASSWORD"
arch-chroot /mnt /bin/bash -c "passwd"
arch-chroot /mnt /bin/bash -c "useradd -mg wheel rfacun"
info_message ">> ENTER USER PASSWORD"
arch-chroot /mnt /bin/bash -c "passwd rfacun"
arch-chroot /mnt /bin/bash -c "sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers"
arch-chroot /mnt /bin/bash -c "sed -i '86i\Defaults !tty_tickets' /etc/sudoers"


# COPY SETUP FILE
# maybe the setup script can be put here as a chroot command to make the script fully automatic
info_message ">> COPYING SETUP FILE"
cp setup /mnt/home/rfacun/
cp package-list /mnt/home/rfacun/
arch-chroot /mnt /bin/bash -c "chown rfacun:wheel /home/rfacun/setup"
arch-chroot /mnt /bin/bash -c "chown rfacun:wheel /home/rfacun/package-list"
success_message ">> DONE!"


# EXIT THE INSTALLATION
success_message ">> INSTALLATION DONE! REBOOTING IN 5 SECONDS..."
sleep 5
umount -R /mnt
reboot
