#!/bin/sh

# check packages
#anki-bin
#font-preview
#julia-bin
#ly-git
#macchina
#montserrat-ttf
#mpdris2
#pam-gnupg
#python-pylspci
#swaylock-effects-git
#url-view
#xdg-ninja
#xmousepasteblock-git

# todo
#   configurar automaticamente ufw
#   agregar binds de ffmpeg (picture, audio, video w/o audio, video w/ audio)
#   agregar bind de sxiv
#   agregar bind de scrot
#   checkear como trabajar con docx, latex
#   agregar bind y scripts para montar y desmontar automáticamente
#   agregar config file y scripts para fzf
#   find dedup program
#   configurar con arkenfox user.js
#   en el futuro configurar dunst
#   checkear si tengo que descomentar o no inglés en ISO
#   armar script de hex color converter (todos los formatos + sepctrwm, etc.)
#   script fzf de todos los configs
#   script fzf de pelis
#   script fzf de cambio de colorscheme
#   aliases de todos los programas
#   hotkeys de todos losp rogramams
#   set up firewall

# Vaiables
col_red="\033[1;31m"
col_grn="\033[1;32m"
col_ylw="\033[1;33m"
col_cyn="\033[1;36m"
col_non="\033[0m"

# Functions
message_good() {
    printf "%b>> %s %b\n\n" "$col_grn" "${1}" "$col_non" ; sleep 3
}

message_bad() {
    printf "%b>> %s %b\n" "$col_red" "${1}" "$col_non"
}

message_ugly() {
    printf "%b>> %s %b\n" "$col_ylw" "${1}" "$col_non"
}

message_normal() {
    printf "%b>> %s %b\n" "$col_cyn" "${1}" "$col_non"
}

intial_configuration() {
    message_normal "Updating the system..."
    sudo pacman --noconfirm -Syu

    message_normal "Changing system keybaord settings..."
    localectl set-keymap la-latin1

    message_normal "Installing AUR helper (yay)..."
    [ -d "$HOME/yay/" ] && rm -rf "yay/"
    git clone https://aur.archlinux.org/yay.git
    (cd yay/ &&  makepkg -si --noconfirm)

    message_good "System initial configuration done!"
}

git_config() {
    message_normal "Configuring git..."

    git config --global user.name "rfacun"
    git config --global user.email "rossi_facundo@outlook.com"
    git config --global credential.helper cache --timeout=21600

    message_good "Updated user name, email and credential cache."
}

dotfiles_config() {
    move_pacman() {
        sudo chown root:root "$HOME/etc/pacman.conf"
        sudo mv "$HOME/etc/pacman.conf" /etc/
    }

    move_amd_conf() {
        sudo mkdir -p /etc/X11/xorg.conf.d/
        sudo chown root:root "$HOME/etc/X11/xorg.conf.d/20-amdgpu.conf"
        sudo mv "$HOME/etc/X11/xorg.conf.d/20-amdgpu.conf" /etc/X11/xorg.conf.d/
    }

    message_normal "Cloning the dotfiles..."

    [ -f "$HOME/.bashrc" ] && rm -rf "$HOME/.bashrc"
    [ -f "$HOME/.bash_profile" ] && rm -rf "$HOME/.bashrc"
    [ -d "$HOME/.dotfiles/" ] && rm -rf "$HOME/.dotfiles/"
    printf ".dotfiles/" > "$HOME/.gitignore"

    # This line clones the repo
    git clone --bare https://github.com/rfacun/dotfiles.git "$HOME/.dotfiles/"

    git --git-dir="$HOME/.dotfiles/" --work-tree="$HOME" config --local status.showUntrackedFiles no
    git --git-dir="$HOME/.dotfiles/" --work-tree="$HOME" checkout

    message_good "Finished cloning the dotfiles."

    message_normal "Moving files to proper directories..."
    move_pacman && move_amd_conf

    message_good "Done moving files."
}

package_install() {
    message_normal "Installing packages..."

    yay -Syu --noconfirm

    # This line installs all the packages
    awk '!/^ *#/ && NF' package-list | xargs yay -S --noconfirm

    message_normal "Installing \"Hack Nerd Font\"..."
    curl -OL https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/Hack.zip
    sudo unzip "Hack.zip" -d /usr/share/fonts/ && fc-cache

    message_good "Finished installing packages."
}

clone_repos() {
    message_normal "Cloning and installing \"dwm\"..."
    git clone https://github.com/rfacun/dwm.git "$HOME/.config/dwm/"
    (cd "$HOME/.config/dwm/" && sudo make clean install)

    message_normal "Cloning and installing \"dwmblocks\"..."
    git clone https://github.com/rfacun/dwmblocks.git "$HOME/.config/dwmblocks/"
    (cd "$HOME/.config/dwmblocks/" && sudo make clean install)

    message_normal "Cloning and installing \"dmenu\"..."
    git clone https://github.com/rfacun/dmenu.git "$HOME/.config/dmenu/"
    (cd "$HOME/.config/dmenu/" && sudo make clean install)

    message_good "Finished cloning and installing programs."
}

clean_up() {
    message_normal "Cleaning up the \$HOME directory"

    message_normal "Making folders..."
    mkdir -p "$HOME/documents/"
    mkdir -p "$HOME/downloads/"
    mkdir -p "$HOME/media/xsecurelock/"
    mkdir -p "$HOME/programming/"

    message_normal "Removing installation files..."
    rm -rf "${HOME:?}/etc/"
    rm -rf "$HOME/Hack.zip"
    rm -rf "$HOME/package-list"
    rm -rf "$HOME/setup"
    rm -rf "$HOME/yay/"

    message_good "Done!! System is ready to be used!"
    message_good "Rebooting in 5 seconds..."
    sleep 5 && reboot
}

welcome (){
    clear ; printf "Start the script? [yes/no] "
    read -r confirm

    case $confirm in
        [Yy][Ee][Ss]) clear ; main ;;
        [Nn][Oo])     exit ;;
    
        *) printf "Please enter a valid option.\n" ; exit ;;
    esac
}

# Main function
main() {
    intial_configuration

    git_config
    dotfiles_config

    package_install
    clone_repos

    clean_up
}

if [ "$(pwd)" != "$HOME" ]; then
    cd "$HOME" && welcome
else
    welcome
fi
