#!/bin/sh

# check packages
#anki-bin
#font-preview
#julia-bin
#ly-git
#macchina
#montserrat-ttf
#mpdris2
#pam-gnupg
#python-pylspci
#swaylock-effects-git
#url-view
#xdg-ninja
#xmousepasteblock-git

# todo
#   configurar automaticamente ufw
#   agregar binds de ffmpeg (picture, audio, video w/o audio, video w/ audio)
#   agregar bind de sxiv
#   agregar bind de scrot
#   checkear como trabajar con docx, latex
#   agregar bind y scripts para montar y desmontar automáticamente
#   agregar config file y scripts para fzf
#   find dedup program
#   configurar con arkenfox user.js
#   en el futuro configurar dunst
#   checkear si tengo que descomentar o no inglés en ISO
#   armar script de hex color converter (todos los formatos + sepctrwm, etc.)
#   script fzf de todos los configs
#   script fzf de pelis
#   script fzf de cambio de colorscheme
#   aliases de todos los programas
#   hotkeys de todos losp rogramams
#   set up firewall


setup_script() {
    printf ">> Updating the system...\n"
    sudo pacman --noconfirm -Syu
    printf ">> Installing AUR helper (yay)...\n"
    [ -d "$HOME/yay/" ] && rm -rf "yay/"
    git clone https://aur.archlinux.org/yay.git
    (cd yay/ &&  makepkg -si --noconfirm)
    printf ">> Finished updating and installing AUR helper...\n\n" ; sleep 5

    printf ">> Configuring Git...\n"
    git config --global user.name "rfacun"
    git config --global user.email "rossi_facundo@outlook.com"
    git config --global credential.helper cache --timeout=21600
    printf "Updated user name, email and credential cache.\n\n" ; sleep 5

    printf ">> Cloning the dotfiles...\n"
    [ -f "$HOME/.bashrc" ] && rm -rf "$HOME/.bashrc"
    [ -d "$HOME/.dotfiles/" ] && rm -rf "$HOME/.dotfiles/"
    printf ".dotfiles/" > "$HOME/.gitignore"
    # This line clones the repo
    git clone --bare https://github.com/rfacun/dotfiles.git "$HOME/.dotfiles/"
    git --git-dir="$HOME/.dotfiles/" --work-tree="$HOME" config --local status.showUntrackedFiles no
    git --git-dir="$HOME/.dotfiles/" --work-tree="$HOME" checkout
    printf "Dotfiles cloned.\n\n" ; sleep 5

    printf ">> Moving files to proper directories...\n"
    sudo chown root:root "$HOME/etc/pacman.conf"
    sudo mv "$HOME/etc/pacman.conf" /etc/
    sudo mkdir -p /etc/X11/xorg.conf.d/
    sudo chown root:root "$HOME/etc/X11/xorg.conf.d/20-amdgpu.conf"
    sudo mv "$HOME/etc/X11/xorg.conf.d/20-amdgpu.conf" /etc/X11/xorg.conf.d/
    printf "Files were moved.\n\n" ; sleep 5

    printf ">> Installing packages...\n"
    yay -Syu
    # This line installs all the packages
    awk '!/^ *#/ && NF' package-list | xargs yay -S --noconfirm
    curl -OL https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/Hack.zip
    sudo unzip "Hack.zip" -d /usr/share/fonts/ && fc-cache
    printf "Packages installed.\n\n" ; sleep 5

    printf ">> Cloning programs (DWM, DWMBLOCKS, DMENU)...\n"
    git clone https://github.com/rfacun/dwm.git "$HOME/.config/dwm/"
    (cd $HOME/.config/dwm/ && sudo make clean install)
    git clone https://github.com/rfacun/dwmblocks.git "$HOME/.config/dwmblocks/"
    (cd $HOME/.config/dwmblocks/ && sudo make clean install)
    git clone https://github.com/rfacun/dmenu.git "$HOME/.config/dmenu/"
    (cd $HOME/.config/dmenu/ && sudo make clean install)
    printf "Programs cloned.\n\n" ; sleep 5

    printf ">> Cleaning up \$HOME...\n"
    rm -rf "$HOME/yay/"
    rm -rf "$HOME/etc/"
    rm -rf "$HOME/Hack.zip"
    printf "Removed unnecessary files.\n\n" ; sleep 5

    printf ">> Setup done! Rebooting in 5 seconds..."
    sleep 5 && reboot
}

[ pwd != "$HOME" ] && cd "$HOME"
clear
printf "Start the script? [Y/n] "
read -r confirm
case $confirm in
    [Yy][Ee][Ss]|[Yy]) clear ; setup_script ; break ;;
    [Nn][Oo]|[Nn])     exit 0 ;;

    *) printf "Please enter a valid option.\n" ; exit 1 ;;
esac
