#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2155

# Bash config
[ -f "$XDG_CONFIG_HOME/bash/bashrc" ] && . "$XDG_CONFIG_HOME/bash/bashrc"

# $PATH directories
export PATH="$PATH:$HOME/.local/bin"

# Directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export NOTES_DIR="$(xdg-user-dir DOCUMENTS)/notes"
export SCREENSAVERS="$HOME/media/screensavers"

# Screen locker
export XSECURELOCK_AUTH_TIMEOUT=5
export XSECURELOCK_IMAGE_DURATION_SECONDS=3
export XSECURELOCK_LIST_VIDEOS_COMMAND="fd . $SCREENSAVERS --type f"
export XSECURELOCK_SAVER="saver_mpv"
export XSECURELOCK_SHOW_KEYBOARD_LAYOUT=0 # Not implemented in 1.8.0

# Programs
export BROWSER="firefox"
export EDITOR="nvim"
export TERM="alacritty"
export PAPE="$(xdg-user-dir PICTURES)/mars-2.jpg"

# Programs' settings
export FZF_DEFAULT_COMMAND="fd --hidden --no-ignore . $HOME"
export FZF_DEFAULT_OPTS="--no-scrollbar --no-border --layout=reverse --color=bg+:-1"

export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="auto verbose name git"
export GIT_PS1_SHOWCOLORHINTS=1
#export GIT_PS1_SHOWSTASHSTATE=1
#export GIT_PS1_SHOWCONFLICTSTATE="yes"
#export GIT_PS1_DESCRIBE_STYLE="branch"

export PROMPT_DIRTRIM=1
export PROMPT_COMMAND="build_prompt"

export HISTFILE="$XDG_CONFIG_HOME/bash/history"
export XINITRC="$XDG_CONFIG_HOME/x/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
#startx "$XINITRC"
