# General
q           quit                                        # quit mpv
Space       cycle pause                                 # pause media
f           cycle fullscreen                            # toggle fullscreen
Shift+i     script-binding stats/display-stats-toggle   # toggle media info
|           script-binding console/enable               # open the console

# Seeking
RIGHT       seek 10                 # forward 10 seconds
LEFT        seek -10                # backward 10 seconds
Shift+RIGHT seek 60                 # forward 60 seconds
Shift+LEFT  seek -60                # backward 60 seconds
0           seek 0 absolute         # go to the first photogram
.           frame-step              # advance one frame and pause
,           frame-back-step         # go back by one frame and pause
}           playlist-next           # skip to the next file
{           playlist-prev           # skip to the previous file

# Video
;           add speed -0.25         # decrease playback speed
:           add speed 0.25          # increase playback speed
-           set speed 1             # reset playback speed
x           ab-loop                 # set/clear A-B loop points

# Audio
v           add volume 10           # add volume (10)
Shift+v     add volume -10          # decrease volume (10)
m           cycle mute              # mute/unmute media

# Subs
Ctrl+z      add sub-delay -0.1      # shift subtitles 100 ms earlier
Ctrl+x      add sub-delay +0.1      # delay subtitles by 100 ms
Ctrl+RIGHT  add sub-scale +0.1      # increase the subtitle font size
Ctrl+LEFT   add sub-scale -0.1      # decrease the subtitle font size
Ctrl+UP     add sub-pos -1          # move subtitles up
Ctrl+DOWN   add sub-pos +1          # move subtitles down
Ctrl+s      cycle sub-visibility    # hide or show the subtitles
s           cycle sub               # switch subtitle track
