#!/bin/sh

xrandr\
    --output DisplayPort-0 --off\
    --output DisplayPort-1 --mode 1440x900 --pos 1920x180 --rotate normal\
    --output DisplayPort-2 --off\
    --output HDMI-A-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal\
    --output DVI-D-0 --off
