#!/bin/sh

monlayout
xset s off -dpms
xwallpaper --maximize "$PAPE"

[ -f "$XDG_CONFIG_HOME/x/xresources" ] && xrdb -merge -I "$XDG_CONFIG_HOME/x/xresources"

programs="numlockx sxhkd transmission-daemon redshift dwmblocks"
for program in $programs; do
    pidof -sx "$program" || "$program" &
done > /dev/null 2>&1

exec dwm
