#!/bin/sh

fnd() {
    cd "$(find \
        "$XDG_CONFIG_HOME" \
        "$HOME/.scripts" \
        "$DOCS" \
        "$DOWNLOADS" \
        "$MEDIA" \
        "$PROGRAMMING" \
        -type d | fzf)" || exit
}
