#!/bin/sh
# Fuzzy find documents

doc="$(find "$DOCS" "$DOWNLOADS" \
    -type f \( -iname "*.pdf" -o -iname "*.epub" -o -iname "*.djvu" \) | fzf $FZF_DEFAULT_OPTS)"

if [ -z "$doc" ]; then
    exit
else
    zathura --mode fullscreen "$doc" > /dev/null 2>&1
fi
