#!/bin/sh
# A giant alias to make videos as fast as possible...

sink=$(pactl list short sinks | cut -f1)
output="$HOME/media/recordings/$(date "+%Y%m%d_%H%M%S_video.mp4")"

# lossy video with audio (video: h264 codec, audio: aac codec)
printf "Now recording...\n"
ffmpeg -loglevel quiet \
    -f x11grab -framerate 30 -s 1920x1080 -i "$DISPLAY" \
    -f pulse -i "$sink" \
    -c:v libx264 -c:a aac -preset ultrafast "$output"
printf "Recording done!\n"
